/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommissionRouteImport } from './routes/commission'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MainIndicatorsRouteImport } from './routes/main-indicators'
import { Route as MapRouteImport } from './routes/map'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ReportsAnnualRouteImport } from './routes/reports.annual'
import { Route as ReportsInternationalRouteImport } from './routes/reports.international'
import { Route as ReportsSpecializedRouteImport } from './routes/reports.specialized'
import { Route as ReportsSurveysRouteImport } from './routes/reports.surveys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRoute = CommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndicatorsRoute = MainIndicatorsRouteImport.update({
  id: '/main-indicators',
  path: '/main-indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAnnualRoute = ReportsAnnualRouteImport.update({
  id: '/annual',
  path: '/annual',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsInternationalRoute = ReportsInternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSpecializedRoute = ReportsSpecializedRouteImport.update({
  id: '/specialized',
  path: '/specialized',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSurveysRoute = ReportsSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commission': typeof CommissionRoute
  '/concepts': typeof ConceptsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/indicators': typeof IndicatorsRoute
  '/journey': typeof JourneyRoute
  '/main-indicators': typeof MainIndicatorsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/reports/annual': typeof ReportsAnnualRoute
  '/reports/international': typeof ReportsInternationalRoute
  '/reports/specialized': typeof ReportsSpecializedRoute
  '/reports/surveys': typeof ReportsSurveysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commission': typeof CommissionRoute
  '/concepts': typeof ConceptsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/indicators': typeof IndicatorsRoute
  '/journey': typeof JourneyRoute
  '/main-indicators': typeof MainIndicatorsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/reports/annual': typeof ReportsAnnualRoute
  '/reports/international': typeof ReportsInternationalRoute
  '/reports/specialized': typeof ReportsSpecializedRoute
  '/reports/surveys': typeof ReportsSurveysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commission': typeof CommissionRoute
  '/concepts': typeof ConceptsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/indicators': typeof IndicatorsRoute
  '/journey': typeof JourneyRoute
  '/main-indicators': typeof MainIndicatorsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/reports/annual': typeof ReportsAnnualRoute
  '/reports/international': typeof ReportsInternationalRoute
  '/reports/specialized': typeof ReportsSpecializedRoute
  '/reports/surveys': typeof ReportsSurveysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commission'
    | '/concepts'
    | '/contact'
    | '/dashboard'
    | '/indicators'
    | '/journey'
    | '/main-indicators'
    | '/map'
    | '/methodology'
    | '/reports'
    | '/sitemap.xml'
    | '/stories'
    | '/reports/annual'
    | '/reports/international'
    | '/reports/specialized'
    | '/reports/surveys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commission'
    | '/concepts'
    | '/contact'
    | '/dashboard'
    | '/indicators'
    | '/journey'
    | '/main-indicators'
    | '/map'
    | '/methodology'
    | '/reports'
    | '/sitemap.xml'
    | '/stories'
    | '/reports/annual'
    | '/reports/international'
    | '/reports/specialized'
    | '/reports/surveys'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commission'
    | '/concepts'
    | '/contact'
    | '/dashboard'
    | '/indicators'
    | '/journey'
    | '/main-indicators'
    | '/map'
    | '/methodology'
    | '/reports'
    | '/sitemap.xml'
    | '/stories'
    | '/reports/annual'
    | '/reports/international'
    | '/reports/specialized'
    | '/reports/surveys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommissionRoute: typeof CommissionRoute
  ConceptsRoute: typeof ConceptsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  IndicatorsRoute: typeof IndicatorsRoute
  JourneyRoute: typeof JourneyRoute
  MainIndicatorsRoute: typeof MainIndicatorsRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission': {
      id: '/commission'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof CommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-indicators': {
      id: '/main-indicators'
      path: '/main-indicators'
      fullPath: '/main-indicators'
      preLoaderRoute: typeof MainIndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/annual': {
      id: '/reports/annual'
      path: '/annual'
      fullPath: '/reports/annual'
      preLoaderRoute: typeof ReportsAnnualRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/international': {
      id: '/reports/international'
      path: '/international'
      fullPath: '/reports/international'
      preLoaderRoute: typeof ReportsInternationalRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/specialized': {
      id: '/reports/specialized'
      path: '/specialized'
      fullPath: '/reports/specialized'
      preLoaderRoute: typeof ReportsSpecializedRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/surveys': {
      id: '/reports/surveys'
      path: '/surveys'
      fullPath: '/reports/surveys'
      preLoaderRoute: typeof ReportsSurveysRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsAnnualRoute: typeof ReportsAnnualRoute
  ReportsInternationalRoute: typeof ReportsInternationalRoute
  ReportsSpecializedRoute: typeof ReportsSpecializedRoute
  ReportsSurveysRoute: typeof ReportsSurveysRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAnnualRoute: ReportsAnnualRoute,
  ReportsInternationalRoute: ReportsInternationalRoute,
  ReportsSpecializedRoute: ReportsSpecializedRoute,
  ReportsSurveysRoute: ReportsSurveysRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommissionRoute: CommissionRoute,
  ConceptsRoute: ConceptsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  IndicatorsRoute: IndicatorsRoute,
  JourneyRoute: JourneyRoute,
  MainIndicatorsRoute: MainIndicatorsRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
